# Generated by Django 3.2.6 on 2021-09-13 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('car_id', models.IntegerField(primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=25)),
                ('brand', models.CharField(max_length=25)),
                ('year', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=25)),
                ('phone_number', models.CharField(max_length=25)),
                ('email_address', models.CharField(max_length=50)),
                ('is_Admin', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Rental_Car',
            fields=[
                ('rent_id', models.IntegerField(primary_key=True, serialize=False)),
                ('fee_per_day', models.IntegerField()),
                ('availability', models.SmallIntegerField()),
                ('car_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.car')),
            ],
        ),
    ]
