# Generated by Django 3.2.6 on 2021-09-13 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210913_1248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_Admin',
            new_name='is_admin',
        ),
    ]
