# Generated by Django 3.2.7 on 2021-09-14 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_is_admin_user_is_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('pickup_location', models.CharField(max_length=50)),
                ('dropoff_location', models.CharField(max_length=50)),
                ('pickup_date', models.DateField()),
                ('dropoff_date', models.DateField()),
                ('pickup_time', models.TimeField()),
                ('dropoff_time', models.TimeField()),
                ('rent_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.rental_car')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Confirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.admin')),
                ('booking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.booking')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('bill_no', models.AutoField(primary_key=True, serialize=False)),
                ('total_fee', models.IntegerField()),
                ('booking_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.booking')),
            ],
        ),
    ]
