# Generated by Django 3.2.7 on 2021-09-14 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_admin_bill_booking_confirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='total_fee',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='rental_car',
            name='fee_per_day',
            field=models.FloatField(),
        ),
    ]
