# Generated by Django 3.2.7 on 2021-09-14 04:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210914_0435'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmation',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
