# Generated by Django 3.2.7 on 2021-10-08 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_booking_rent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='booking_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.booking'),
        ),
    ]
