# Generated by Django 3.2.7 on 2021-10-13 01:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_bill_booking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmation',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
