# Generated by Django 3.2.7 on 2021-10-13 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_admin_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='role',
            field=models.CharField(default='Sales Department', max_length=25),
        ),
    ]
