# Generated by Django 3.2.7 on 2021-10-13 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_admin_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='role',
            field=models.CharField(default='Sales', max_length=25),
        ),
    ]
